apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webcicd-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: web.demo
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webcicd
            port:
              number: 80
